(ns iou-tracker.views
  (:require [hiccup.core :refer [html]]
            [hiccup.page :refer [html5 include-css]]
            [cheshire.core :as json]))

;; ---------------------------------------------------------------------------
;; Shared layout
;; ---------------------------------------------------------------------------

(defn- page [title & body]
  (html5
    [:head
     [:meta {:charset "utf-8"}]
     [:meta {:name "viewport" :content "width=device-width, initial-scale=1"}]
     [:title title]
     (include-css "/style.css")]
    (into [:body] body)))

;; ---------------------------------------------------------------------------
;; Landing page
;; ---------------------------------------------------------------------------

(defn landing []
  (page "IOU Tracker"
    [:div.container
     [:h1 "IOU Tracker"]
     [:p.tagline "Track shared expenses by SMS — no app, no bank account needed."]
     [:div.steps
      [:h2 "How it works"]
      [:ol
       [:li "Text your IOU to the number: " [:code "17.50 for pizza from Maria"]]
       [:li "Get an instant confirmation by SMS"]
       [:li "Text " [:code "balance"] " any time to see what you owe"]
       [:li "Text " [:code "settle Maria"] " to get a printable receipt"]
       [:li "Meet in person, exchange cash, tap the receipt to mark it settled"]]]
     [:div.commands
      [:h2 "Commands"]
      [:table
       [:thead [:tr [:th "Text"] [:th "What it does"]]]
       [:tbody
        [:tr [:td [:code "{amount} for {item} from {name}"]] [:td "Record a debt"]]
        [:tr [:td [:code "balance"]]                          [:td "See all you owe"]]
        [:tr [:td [:code "settle {name}"]]                   [:td "Get a printable receipt"]]
        [:tr [:td [:code "name {yourname}"]]                 [:td "Set your display name"]]
        [:tr [:td [:code "help"]]                            [:td "Show command list"]]]]]]))

;; ---------------------------------------------------------------------------
;; Receipt page
;; ---------------------------------------------------------------------------

(defn- format-amount [n]
  (format "$%.2f" (double n)))

(defn- parse-debt-details [json-str]
  (try (json/parse-string json-str true)
       (catch Exception _ [])))

(defn receipt [receipt-row]
  (let [{:keys [token debtor_phone debtor_name creditor_name
                total_amount debt_details status created_at settled_at]} receipt-row
        debts    (parse-debt-details debt_details)
        settled? (= status "settled")
        debtor   (or debtor_name debtor_phone)]
    (page (str "IOU Receipt — " debtor " owes " creditor_name)
      [:div.receipt {:id "receipt"}
       [:div.receipt-header
        [:h1 "IOU Receipt"]
        [:p.receipt-date "Generated: " created_at]]

       [:div.receipt-parties
        [:div.party
         [:span.label "From (owes)"]
         [:span.value debtor]]
        [:div.arrow "→"]
        [:div.party
         [:span.label "To (owed)"]
         [:span.value creditor_name]]]

       [:div.receipt-items
        [:h3 "Itemized"]
        [:table
         [:thead [:tr [:th "Description"] [:th "Amount"] [:th "Date"]]]
         [:tbody
          (for [d debts]
            [:tr
             [:td (:description d)]
             [:td (format-amount (:amount d))]
             [:td (:created_at d)]])]]]

       [:div.receipt-total
        [:span "Total"]
        [:span.total-amount (format-amount total_amount)]]

       (if settled?
         [:div.settled-banner
          [:p "✓ SETTLED on " settled_at]]
         [:div.settle-section
          [:p "When you've exchanged cash or goods, tap the button below to mark this receipt settled."]
          [:form {:method "POST" :action (str "/receipt/" token "/settle")}
           [:button.settle-btn {:type "submit"} "Mark as Settled"]]])

       [:div.receipt-footer
        [:p "This receipt was generated by IOU Tracker. No money was moved — this is a record only."]
        [:a {:href "#" :onclick "window.print(); return false;"} "Print this receipt"]]])))

;; ---------------------------------------------------------------------------
;; Error / not-found
;; ---------------------------------------------------------------------------

(defn not-found []
  (page "Not Found"
    [:div.container
     [:h1 "404"]
     [:p "Receipt not found. The link may have expired or been mistyped."]
     [:a {:href "/"} "← Back to home"]]))

(defn already-settled [receipt-row]
  (page "Already Settled"
    [:div.container
     [:h1 "Already settled"]
     [:p "This receipt was already marked as settled on " (:settled_at receipt-row) "."]
     [:a {:href (str "/receipt/" (:token receipt-row))} "View receipt"]]))
